// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMaFUTVi1nGUFoe_veIeqPBax9XDi0hNo',
    appId: '1:812212502944:web:50c864274177c8f3aaa4c5',
    messagingSenderId: '812212502944',
    projectId: 'student-planner-app-97c0e',
    authDomain: 'student-planner-app-97c0e.firebaseapp.com',
    storageBucket: 'student-planner-app-97c0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwgRXJkh7O3NjniQsdi0JUgxeWrRNhQqE',
    appId: '1:812212502944:android:9ba3e320168d69c1aaa4c5',
    messagingSenderId: '812212502944',
    projectId: 'student-planner-app-97c0e',
    storageBucket: 'student-planner-app-97c0e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMaFUTVi1nGUFoe_veIeqPBax9XDi0hNo',
    appId: '1:812212502944:web:ea6630ab1893a11eaaa4c5',
    messagingSenderId: '812212502944',
    projectId: 'student-planner-app-97c0e',
    authDomain: 'student-planner-app-97c0e.firebaseapp.com',
    storageBucket: 'student-planner-app-97c0e.firebasestorage.app',
  );
}
