import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
 

// Import your Firebase options file (usually auto-generated by FlutterFire CLI)
import 'firebase_options.dart';

// Import your pages
import 'starter_page.dart';
import 'home_page.dart';
import 'action_page.dart';
import 'create_group_page.dart';

 

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Flutter bindings are initialized
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    ); // Initialize Firebase
    print("✅ Firebase has been initialized successfully!");
  } catch (e) {
    print("❌ Error initializing Firebase: $e");
  }

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Auto Prompt',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/', // Set the initial route
      routes: {
       '/': (context) => const StarterPage(),
       '/home': (context) => const HomePage(),
      '/action': (context) => const ActionPage(),
      '/create_group': (context) => const CreateGroupPage(),

      },
    );
  }
}